/**
 * Candlepin
 * Server for fake Candlepin application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: joseph.stone@dataductus.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("gameGameIdRollPut", () => {
    const gameId: string = "gameId_example"
    const body: api.GameIdRollBody = undefined
    return expect(instance.gameGameIdRollPut(gameId, body, {})).resolves.toBe(null)
  })
  test("gamesGet", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.gamesGet(id, {})).resolves.toBe(null)
  })
})

